version: '3'
services:
  detector-batch:
    image: detector-batch
    container_name: detector-batch-20210510115942
    networks:
    - network-detector-inference-mnist
    depends_on:
    - tracker-detector-inference-mnist
    environment:
      MLFLOW_TRACKING_URI: http://tracker-detector-inference-mnist:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/:/executor
    - /home/guess/Desktop/scanflow/examples/demo_mnist/stuff/tracker/tracker-detector-inference-mnist:/mlflow
  tracker-detector-inference-mnist:
    image: tracker-detector-inference-mnist
    container_name: tracker-detector-inference-mnist-20210510115942
    networks:
    - network-detector-inference-mnist
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/stuff/tracker/tracker-detector-inference-mnist:/mlflow
    ports:
    - 8007:8002
networks:
  network_detector-inference-mnist: null
