version: '3'
services:
  modeling1:
    image: modeling1
    container_name: modeling1-20200327112721
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
  inference:
    image: inference
    container_name: inference-20200327112721
    networks:
    - network-workflow1
    depends_on:
    - tracker-workflow1
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow1:8001
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
  tracker-workflow1:
    image: tracker-workflow1
    container_name: tracker-workflow1-20200327112721
    networks:
    - network-workflow1
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow1:/mlflow
    ports:
    - 8006:8001
  modeling2:
    image: modeling2
    container_name: modeling2-20200327112721
    networks:
    - network-workflow2
    depends_on:
    - tracker-workflow2
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow2:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow2:/mlflow
  optimizer:
    image: optimizer
    container_name: optimizer-20200327112721
    networks:
    - network-workflow2
    depends_on:
    - tracker-workflow2
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow2:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow2:/mlflow
  inference_intel:
    image: inference_intel
    container_name: inference_intel-20200327112721
    networks:
    - network-workflow2
    depends_on:
    - tracker-workflow2
    environment:
      MLFLOW_TRACKING_URI: http://tracker-workflow2:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/:/app
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow2:/mlflow
  tracker-workflow2:
    image: tracker-workflow2
    container_name: tracker-workflow2-20200327112721
    networks:
    - network-workflow2
    volumes:
    - /home/guess/Desktop/scanflow/examples/intel_openvino/data-science/ad-stuff/ad-tracker/tracker-workflow2:/mlflow
    ports:
    - 8007:8002
networks:
  network_workflow1: null
  network_workflow2: null
