version: '3'
services:
  inference-batch:
    image: inference-batch
    container_name: inference-batch-20210419190204
    networks:
    - network-inference-mnist
    depends_on:
    - tracker-inference-mnist
    environment:
      MLFLOW_TRACKING_URI: http://tracker-inference-mnist:8002
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/:/executor
    - /home/guess/Desktop/scanflow/examples/demo_mnist/stuff/tracker/tracker-inference-mnist:/mlflow
    tty: 'true'
  tracker-inference-mnist:
    image: tracker-inference-mnist
    container_name: tracker-inference-mnist-20210419190204
    networks:
    - network-inference-mnist
    volumes:
    - /home/guess/Desktop/scanflow/examples/demo_mnist/stuff/tracker/tracker-inference-mnist:/mlflow
    ports:
    - 8007:8002
networks:
  network_inference-mnist: null
